### ISSUE TITLE
how to build arwrapper from source

### ISSUE THREAD

**Issue by yichuan1118** [artoolkitx/arunity5#1]
I would like to customize some code in arWrapper for unity, how do I build it from source? Thanks!

**Comment by ThorstenBux** [comment]
You mean that: https://github.com/artoolkitx/arunity5/tree/master/src/Android_Unity_Player_Source/AndroidStudioProj

?

**Comment by yichuan1118** [comment]
I mean the this repo (arunity 5) is shipping with some binary files, for example: arunity5/src/Unity/Assets/Plugins/iOS/

how to build these binary from source? Thank you!

**Comment by ThorstenBux** [comment]
You build artoolkitx https://github.com/artoolkitx/artoolkit5 from source after you made your changes
