### ISSUE TITLE
iOS build - Apple Mach-O Linker (Id) Error

### ISSUE THREAD

**Issue by slowizzm** [artoolkitx/arunity5#5]
Ld /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Products/ReleaseForRunning-iphoneos/ProductName.app/ProductName normal armv7
    cd /Users/slow_izzm/Documents/Unity/AR/burner/builds/burner2
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Users/slow_izzm/Downloads/Xcode-beta 3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/slow_izzm/Downloads/Xcode-beta 3.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Users/slow_izzm/Downloads/Xcode-beta\ 3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch armv7 -isysroot /Users/slow_izzm/Downloads/Xcode-beta\ 3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -L/Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Products/ReleaseForRunning-iphoneos -L/Users/slow_izzm/Documents/Unity/AR/burner/builds/burner2 -L/Users/slow_izzm/Documents/Unity/AR/burner/builds/burner2/Libraries -L/Users/slow_izzm/Documents/Unity/AR/burner/builds/burner2/Libraries/Plugins/iOS -F/Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Products/ReleaseForRunning-iphoneos -filelist /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/armv7/ProductName.LinkFileList -miphoneos-version-min=7.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/armv7/ProductName_lto.o -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -lstdc++.6 -lsqlite3 -framework MediaToolbox -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lcurl -lboost_serialization -lARWrapper -ljpeg -lAR -framework MobileCoreServices -framework Security -framework Accelerate -framework GameKit -weak_framework Metal -Xlinker -dependency_info -Xlinker /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/armv7/ProductName_dependency_info.dat -o /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Products/ReleaseForRunning-iphoneos/ProductName.app/ProductName

    Undefined symbols for architecture armv7:
      "_inflate", referenced from:
      _inflate_stream in libcurl.a(libcurl_la-content_encoding.o)
     (maybe you meant: _inflate_copyright, _unity_z_inflateCopy , _unity_z_inflateSync , _unity_z_inflateGetHeader , _inflate_table , _unity_z_inflatePrime , _unity_z_inflateSetDictionary , __Z27scripting_class_is_inflated17ScriptingClassPtr , _inflated_classes_size , _inflated_methods_size , _mono_class_inflate_generic_type_with_mempool , _mono_method_inflated_lookup , _mono_metadata_free_inflated_signature , _mono_get_inflated_method , _mono_marshal_free_inflated_wrappers , _mono_class_inflate_generic_method_full_checked , _mono_metadata_inflate_generic_inst , _inflated_classes , _unity_z_inflateInit_ , _unity_z_inflateReset , _mono_class_inflate_generic_class , _unity_z_inflateEnd , _mono_class_inflate_generic_method_full , _mono_metadata_get_inflated_signature , _unity_z_inflateSyncPoint , _mono_class_is_inflated , _mono_class_inflate_generic_method , _unity_z_inflateInit2_ , _mono_class_get_inflated_method , _unity_z_inflate , _inflate_fast , _unity_mono_method_is_inflated , _mono_class_inflate_generic_type , _mono_class_inflate_generic_type_checked )
      "_zlibVersion", referenced from:
      _Curl_unencode_gzip_write in libcurl.a(libcurl_la-content_encoding.o)
     (maybe you meant: _unity_z_zlibVersion)
      "_inflateInit2_", referenced from:
      _inflate_stream in libcurl.a(libcurl_la-content_encoding.o)
      _Curl_unencode_gzip_write in libcurl.a(libcurl_la-content_encoding.o)
     (maybe you meant: _unity_z_inflateInit2_)
      "_inflateEnd", referenced from:
      _inflate_stream in libcurl.a(libcurl_la-content_encoding.o)
      _Curl_unencode_gzip_write in libcurl.a(libcurl_la-content_encoding.o)
      _Curl_unencode_cleanup in libcurl.a(libcurl_la-content_encoding.o)
     (maybe you meant: _unity_z_inflateEnd)
      "_inflateInit_", referenced from:
      _Curl_unencode_deflate_write in libcurl.a(libcurl_la-content_encoding.o)
     (maybe you meant: _unity_z_inflateInit_)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Not sure what to do from here ... I had a similar issue when building ARToolKit 6, the fix there was to remove "" from the library paths. I have tried that here and continue getting these same 6 errors.

**Comment by slowizzm** [comment]
I switched from IL2CPP to Mono and have reduced to 1 error ... 

    Ld /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Products/ReleaseForRunning-iphoneos/ar.app/ar normal armv7
    cd /Users/slow_izzm/Documents/Unity/AR/burner/builds/burner2
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Users/slow_izzm/Downloads/Xcode-beta 3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/slow_izzm/Downloads/Xcode-beta 3.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Users/slow_izzm/Downloads/Xcode-beta\ 3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch armv7 -isysroot /Users/slow_izzm/Downloads/Xcode-beta\ 3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -L/Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Products/ReleaseForRunning-iphoneos -L/Users/slow_izzm/Documents/Unity/AR/burner/builds/burner2 -L/Users/slow_izzm/Documents/Unity/AR/burner/builds/burner2/Libraries -L/Users/slow_izzm/Documents/Unity/AR/burner/builds/burner2/Libraries/Plugins/iOS -F/Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Products/ReleaseForRunning-iphoneos -filelist /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/armv7/ar.LinkFileList -Xlinker -map -Xlinker /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/ar-LinkMap-normal-armv7.txt -miphoneos-version-min=7.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/armv7/ar_lto.o -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -lstdc++.6 -lsqlite3 -framework MediaToolbox -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework MediaPlayer -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -lcurl -lARWrapper -ljpeg -lAR -framework MobileCoreServices -framework Security -framework Accelerate -framework GameKit -weak_framework Metal -Xlinker -dependency_info -Xlinker /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/armv7/ar_dependency_info.dat -o /Users/slow_izzm/Library/Developer/Xcode/DerivedData/Unity-iPhone-gogrmjpgtlnwavbtukevvotxgsuf/Build/Products/ReleaseForRunning-iphoneos/ar.app/ar

    ld: library not found for -lil2cpp

**Comment by philip-lamb** [comment]
You don't need to switch from il2cpp, but you do need to add libz to the linked libraries options. This has been fixed in artoolkitX for Unity, which is due out soon.

**Comment by slowizzm** [comment]
Sounds good, I must have misread, I was under the impression we should stay it in Mono for artk5.

@philip-lamb do you know when we should be excepting the release? looking forward to it.

**Comment by slowizzm** [comment]
Thanks @philip-lamb ... I get the same linker errors with il2cpp. I notice they all say referenced from libcurl.a, but I have this file included in my libraries. I would love to get this to build so I can continue to dev, unless artkx is just around the corner. Are you able to estimate a date of release? Looking forward to it, thanks.

**Comment by slowizzm** [comment]
@philip-lamb

This worked for me ...

“Click "Build Phases" and twirl open "Link Binary With Libraries" and scroll to bottom of the list and click the '+' button. From the displayed list, scroll down to libz.tbd, select it and click the Add button. This fixes the "not found" symbols.”
