### ISSUE TITLE
Unable to start AR tracking when re-entering the app.

### ISSUE THREAD

**Issue by slowizzm** [artoolkitx/arunity5#6]
When I exit the app, like when linking out to a website, upon return I get an error `Unable to start AR tracking. Please check that you have a camera connected.` I occasionally get this error when returning to my AR scene from a non AR scene as well. I tried commenting out the arwSetLog code found in issue [#61](https://github.com/artoolkit/arunity5/issues/61) but still get this error. 

Unity 2017.3.0 and I am currently using the arunity6 version until arunityX is released, but I would still love to solve this issue in the meantime and update my app later. Thanks

![92d7896c-e790-4dba-9148-0d7b07d51b39](https://user-images.githubusercontent.com/14972059/37557269-fa60d276-29cf-11e8-95cc-56d1dc7842be.jpeg)

**Comment by ThorstenBux** [comment]
You get this issue with arunity5 or arunity6?

**Comment by slowizzm** [comment]
@ThorstenBux arunity6 ... I tried to go back to arunity5, but I kept getting a bunch of linker errors #5 and figured I would wait until arunityX is released to get back on track with artk. I can kind of hack around this for the most part, but it's not a neat fix and doesn't work all the time. I would rather solve the issue if that is possible until arunityX is released. 

Do we have an estimated date on when arunityX will be released?

**Comment by ThorstenBux** [comment]
Unfortunately, I can't give support on arunity6 anymore. (Code is private with DAQRI and I'm not with them anymore). I know that it is not easy to switch from arunity6 to arunity5 :(. 

arunityX will be released soon and we are working hard on getting it out.

**Comment by dhawalbanker** [comment]
@ThorstenBux any update on next release of arunity6 from ARToolKitX? I am also wondering how can I help to speed up the process?

**Comment by ThorstenBux** [comment]
It might probably be released within this week if all goes smooth.

**Comment by dhawalbanker** [comment]
We will be eagerly waiting for the announcement.

**Comment by ThorstenBux** [comment]
@dhawalbanker @yg-apaza

It is out now, thanks @philip-lamb https://github.com/artoolkitx/arunityx

**Comment by dhawalbanker** [comment]
Thanks @ThorstenBux for the update.

**Comment by yg-apaza** [comment]
Thanks @ThorstenBux !
